version: '3.10'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Omar1122
      POSTGRES_DB: btc
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8050:8050"
    depends_on:
      - db
    environment:
      - DASH_DEBUG_MODE=True
